# Generated by Django 6.0 on 2026-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
