# Generated by Django 6.1 on 2026-09-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='django_customer',
        ),
    ]
