# Generated by Django 6.1 on 2026-09-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
